version: "3.0"

services:
  start_deps:
    image: dadarek/wait-for-dependencies
    depends_on: 
      - rabbitmq
    command: rabbitmq:5672
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost", "5672" ]
      interval: 10s
      timeout: 30s
      retries: 3  
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports: 
      - 27017:27017
  backend:
    image: rahtoken/rivi:backend
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on: 
      - rabbitmq
      - redis
      - mongo
      - start_deps
  worker:
    image: rahtoken/rivi:worker
    restart: on-failure
    depends_on: 
      - rabbitmq
      - redis
      - mongo
      - start_deps
